name: Prettier Auto-Format

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Run Prettier Formatting
        run: npm run format

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-format with Prettier"
          git push