name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 18.x, latest]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache React Chrome Extension node modules
      id: cache-nodemodules
      uses: actions/cache@v3
      with:
        path: react-chrome-extension/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Installing Dependencies
      if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true'}} 
      run: |
          cd react-chrome-extension
          npm ci

    - name: Build
      run: |
        cd react-chrome-extension
        npm run build
